import type { Metadata } from "next";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";
import type { ICrumbItem } from "@/shared/ui.kit";


export const metadata: Metadata = {

  title: "Home - HONEYMAM",
  description: "Generated by create next app",

};




export default function RootLayout( { children }: Readonly<{ children: React.ReactNode }> ) {

  return (

    <section className="carcass with_bread_crumbs">


      <>{ children }</>


    </section>

  )

}
