import { Footer } from "@/widgets/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <section className={ `carcass with_bread_crumbs` }>
      
      {children}
      <Footer />

    </section>

  )
}
