import type { Metadata } from "next";
import localFont from "next/font/local";
import "./_styles/globals.scss";

const Kosko = localFont( {

  src: [

    {

      path: './_fonts/KoskoBold-Bold.woff2',
      weight: '700',

    },

    {

      path: './_fonts/KoskoRegular-Regular.woff2',
      weight: '400',

    },

  ],

  variable: '--font-kosko'

} );

const myWeekend = localFont( {

  src: [

    {

      path: './_fonts/MV-WEEKEND.otf',
      weight: '400',

    },

  ],

  variable: '--font-myweekend'

} );
const garamondCondensed = localFont( {

  src: [

    {

      path: './_fonts/Garamond_Condensed_Regular.ttf',
      weight: '400',

    },

  ],

  variable: '--font-garamondCondensed'

} );

export const metadata: Metadata = {

  title: "Home - HONEYMAM",
  description: "Generated by create next app",

};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (

    <html lang="ru" className={ `${ Kosko.variable } ${ myWeekend.variable } ${ garamondCondensed.variable } font-sans ` }>

      <body>

        { children }

      </body>

    </html>

  )

}
