import { Footer } from "@/widgets/footer"
import { Suspense } from "react"
import Skeleton from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'
import s from './[id]/product.module.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <section className={ `carcass with_bread_crumbs` }>

      <Suspense fallback = {
          <div className={ s.skeleton }>
            <Skeleton height={'100%'} width={'100%'}/>
            <Skeleton count={10} height={'100%'} width={'100%'}/>
          </div>
      }>{children}</Suspense>

      <Footer />

    </section>

  )
}
